### ISSUE TITLE
Failing windows tests with 2023.2

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLinearAlgebra/MKL.jl#130]
Almost all the tests fail with this. Not sure what is happening here and if it is a Julia issue or something else in MKL.

Seen in #123 and logs in https://github.com/JuliaLinearAlgebra/MKL.jl/actions/runs/5786517472/job/15681397696

```
     From worker 3:	┌ Error: The `LinearAlgebra/bidiag` test set mutated ENV and did not restore the original values
      From worker 3:	│   testset_name = "LinearAlgebra/bidiag"
      From worker 3:	│   testset_path = "C:\\hostedtoolcache\\windows\\julia\\nightly\\x64\\share\\julia\\stdlib\\v1.11\\LinearAlgebra\\test\\bidiag"
      From worker 3:	└ @ Main C:\Users\RUNNER~1\AppData\Local\Temp\jl_HEpvLY\testdefs.jl:56
LinearAlgebra/bidiag               (3) |         failed at 2023-08-07T15:10:53.520
Error During Test at C:\Users\RUNNER~1\AppData\Local\Temp\jl_HEpvLY\testdefs.jl:22
  Got exception outside of a @test
  The `LinearAlgebra/bidiag` test set mutated ENV and did not restore the original values
```

**Comment by imciner2** [comment]
Its tripping up because MKL is leaving the `__KMP_REGISTERED_LIB_<PID>` variable in the environment after the tests are run. This isn't unique to the test environment either, it happens if you just download and run the `pinv.jl` test file with MKL as well. Changing the threading layer (using `MKL.set_threading_layer(MKL.THREADING_TBB)` for instance) before calling it doesn't change anything, so it appears it is always going to be loading the OpenMP library when the shared library is used now.

Probably, the MKL tests should be run with the environment variable `JULIA_TEST_CHECK_MUTATED_ENV` set to false to just ignore that check.
