### ISSUE TITLE
Make LP64 the default

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLinearAlgebra/MKL.jl#4]
Ref https://github.com/JuliaLang/julia/issues/30828

**Comment by ViralBShah** [comment]
This is in a good place for now - so closing the issue.

**Comment by RoyiAvital** [comment]
@ViralBShah , The current state, performance wise, isn't optimal.
If we have dynamic loading of functions, why not use the API according to the properties of the matrix?
It will improve performance. Especially for Sparse Matrices.

**Comment by ViralBShah** [comment]
It is not that dynamic. Also these capabilities are only for blas and lapack, not sparse matrices.

**Comment by RoyiAvital** [comment]
But since the trampoline feature is designed mainly for BLAS / LAPCAK it would be great to have the feature.
If you target me a better place to open such issue I will be happy.
But this holds for any algorithm which works with matrix indices, having an option for 32 Bit indices means performance and throughput might be better.
