### ISSUE TITLE
Error building MKL with JuliaPro (1.5.2-1)

### ISSUE THREAD

**Issue by murari0** [JuliaLinearAlgebra/MKL.jl#57]
I am not able to build MKL.jl on JuliaPro, version 1.5.2-1. It seems to be a path issue of some sort, from this error I see in the [build.log](https://github.com/JuliaComputing/MKL.jl/files/5476781/build.log):

```
error during bootstrap:
LoadError("/tmp/jl_KJBg9y/sysimage_packagecompiler_47f66860-1d26-11eb-158f-992ab58b7eca.jl", 16, ArgumentError("Package MKL not found in current path:\n- Run `import Pkg; Pkg.add(\"MKL\")` to install the MKL package.\n"))
require at ./loading.jl:893
```
I don't quite know how to fix this though. Is there something I'm doing wrong?

System: Ubuntu LTS 18.04 and 20.04

**Comment by ViralBShah** [comment]
@bmharsha

**Comment by bmharsha** [comment]
This issue is occurring because PackageCompiler is not retaining the environment that it started creating the SYSIMG with. @murari0 Can you try following and let us know if this solves the issue?

* Create following folder: 

```
~/.julia/environments/v1.5
```
* Copy the contents of `~/.julia/environments/JuliaPro_v1.5.2-1` folder to `~/.julia/environments/v1.5` (Backup the contents of following folder if you were using this environment: `~/.julia/environments/v1.5` )
```
cp ~/.julia/environments/JuliaPro_v1.5.2-1/* ~/.julia/environments/v1.5
```

**Comment by murari0** [comment]
@bmharsha This works, thanks! Is it ok to revert the contents of the `~/.julia/environments/v1.5` folder after MKL finishes building?

**Comment by bmharsha** [comment]
>Is it ok to revert the contents of the ~/.julia/environments/v1.5 folder after MKL finishes building?

Yes, its ok to revert the contents of `~/.julia/environments/v1.5` after the SYSIMG is built.

**Comment by ViralBShah** [comment]
JuliaPro is now discontinued. Closing this issue.
